---
version: 2
plan:
  project-key: WEBCO
  key: VLUIACCORDION
  name: webcomponent-vl-ui-accordion

triggers:
  - polling: 130
  - cron: 0 0 1,3,12,19,21 ? * * *

variables:
  release_version: patch

stages:
  - Build:
      jobs:
        - Build
  - Release:
      manual: true
      jobs:
        - Release

Build:
  key: BD
  tasks:
    - clean
    - script: |
        #!/usr/env/bin bash
        set -e
        docker-compose -f test/docker-compose.yml up --scale selenium-chrome=3 --scale selenium-firefox=3 --exit-code-from tests
        docker-compose -f docker-compose-performance-chrome.yml up --force-recreate --exit-code-from sitespeed-chrome
        docker-compose -f docker-compose-performance-firefox.yml up --force-recreate --exit-code-from sitespeed-firefox
  final-tasks:
    - script: /opt/scripts/docker/stop-docker-containers.sh
  artifacts:
    - name: Test reports
      location: performance/results/
      pattern: '**/*.xml'
      required: true
    - name: Chrome results
      location: performance/results/chrome/
      pattern: '**/*'
      required: true
    - name: Firefox results
      location: performance/results/firefox
      pattern: '**/*'
      required: true
  requirements:
    - REMOTE_ONLY

Release:
  key: REL
  tasks:
    - clean
    - script: |
        #!/usr/env/bin bash
        set -e
        /opt/scripts/git/git-repository-information-restore.sh
        COMPOSE_OPTIONS="-e git_repo=${bamboo_repository_git_repositoryUrl} -e release_version=${bamboo.release_version}" docker-compose -f docker-compose-release.yml run release
  final-tasks:
    - script: /opt/scripts/docker/stop-docker-containers.sh
  requirements:
    - REMOTE_ONLY

---
version: 2
plan:
  key: WEBCO-VLUIACCORDION

plan-permissions:
  - groups:
      - bamboo-admin
      - bamboo-release
      - developer-admin
    permissions:
      - view
      - edit
      - build
      - clone
      - admin
